/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.emp.gl.gui;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.messages.Anonymous;
import org.emp.gl.messages.BaseMessageAdapter;
import org.emp.gl.messages.Decalage;
import org.emp.gl.messages.IMessage;
import org.emp.gl.messages.Md5;
import org.emp.gl.messages.RemovePonctuation;
import org.emp.gl.messages.RemoveSpaces;
import org.emp.gl.messages.UpperCase;
import org.emp.gl.messages.HashSimple;
import org.emp.gl.sender.service.MessagingService;

/**
 *
 * @author billal
 */
public class MessagingSenderGui extends javax.swing.JFrame {

    private final String senderId;
    static String HASH = "hash";
    static String MD5 = "MD5";
    static String REMOVEPONCTUATION = "remove ponctuation";
    static String REMOVESPACE = "remove space";
    static String UPPERCASE = "upper case";
    static String ANONYMOUS = "anonymous";
    static String DECALAGE = "decalage";
    static IMessage MSG;

    static ArrayList<String> list_decoration = new ArrayList<>();

    static void appliquerDecor(ArrayList<String> list) throws NoSuchAlgorithmException {
        for (String l : list) {
            switch (l) {
                case "hash":
                    MSG = new HashSimple(MSG);
                    break;
                case "MD5":
                    MSG = new Md5(MSG);
                    break;
                case "remove ponctuation":
                    MSG = new RemovePonctuation(MSG);
                    break;
                case "remove space":
                    MSG = new RemoveSpaces(MSG);
                    break;
                case "upper case":
                    MSG = new UpperCase(MSG);
                    break;
                case "anonymous":
                    MSG = new Anonymous(MSG);
                    break;
                case "decalage":
                    MSG = new Decalage(MSG);
                    break;

            }
        }

    }

    void Logger() {
        String k = ">>Les décors appliqués :";
        for (String l : list_decoration) {
            k += l + " ,";
        }
        k += " \n";
        jTextArea1.setText(jTextArea1.getText() + k);

    }

    /**
     * Creates new form MessagingRecievingTest
     */
    public MessagingSenderGui(String senderId) {
        setSize(400, 400);
        this.senderId = senderId;

        initComponents();

        userField.setText(senderId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destinationField = new javax.swing.JTextField();
        objectField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Emetteur :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 31, -1, -1));

        userField.setEditable(false);
        userField.setText("ID-241");
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 28, 241, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Destinataire :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 61, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Objet :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 91, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Message :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        destinationField.setText("ID-1");
        getContentPane().add(destinationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 58, 241, -1));
        getContentPane().add(objectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 88, 241, -1));

        messageField.setColumns(40);
        messageField.setRows(5);
        jScrollPane1.setViewportView(messageField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 350, 180));

        jToggleButton2.setText("supp ponctuation");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 150, -1));

        jToggleButton3.setText("supp espace blanc");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 150, -1));

        jToggleButton4.setText("Majuscule");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        jToggleButton5.setText("MD5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 100, -1));

        jToggleButton6.setText("SimpleHash");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 250, 50));

        jToggleButton7.setText("Décalage");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        jToggleButton8.setText("Anonymous");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 910, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Logger :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 30, 20));

        jLabel6.setText("Filtrage:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel7.setText("Intégrité:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel8.setText("Cryptage:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        jLabel9.setText("Anonymous");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //IMessage message = new BaseMessageAdapter();
        MSG = new BaseMessageAdapter();
        MSG.setTitle(objectField.getText());
        MSG.setMessage(messageField.getText());
        MSG.setSender(userField.getText());
        // IMessage upcase = new UpperCase(message);

        //MSG=new RemovePonctuation(MSG);
        //IMessage rmponc = new RemovePonctuation(upcase);
        //IMessage rmsp = new RemoveSpaces(rmponc);
        // IMessage hashs = new HashSimple(rmsp);
        //IMessage md5 = new Md5(rmsp);
        //MSG=new HashSimple(MSG);
        try {
            appliquerDecor(list_decoration);

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MessagingSenderGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        MessagingService ms = Lookup.getInstance().getService(MessagingService.class);
        ms.sendMessage(destinationField.getText(), MSG.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (list_decoration.contains(REMOVEPONCTUATION)) {
            list_decoration.remove(REMOVEPONCTUATION);

        } else {
            list_decoration.add(REMOVEPONCTUATION);
        }
        Logger();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:

        if (list_decoration.contains(REMOVESPACE)) {
            list_decoration.remove(REMOVESPACE);
        } else {
            list_decoration.add(REMOVESPACE);
        }
        Logger();

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        if (list_decoration.contains(UPPERCASE)) {
            list_decoration.remove(UPPERCASE);
        } else {
            list_decoration.add(UPPERCASE);
        }
        Logger();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        if (list_decoration.contains(MD5)) {
            list_decoration.remove(MD5);
        } else {
            list_decoration.add(MD5);
        }
        Logger();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        if (list_decoration.contains(HASH)) {
            list_decoration.remove(HASH);
        } else {
            list_decoration.add(HASH);
        }
        Logger();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        if (list_decoration.contains(DECALAGE)) {
            list_decoration.remove(DECALAGE);
        } else {
            list_decoration.add(DECALAGE);
        }
        Logger();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        if (list_decoration.contains(ANONYMOUS)) {
            list_decoration.remove(ANONYMOUS);
        } else {
            list_decoration.add(ANONYMOUS);
        }
        Logger();
    }//GEN-LAST:event_jToggleButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField destinationField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JTextArea messageField;
    private javax.swing.JTextField objectField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
